sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && sh run.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

### Add your own lists here
### See https://github.com/INCATools/ontology-starter-kit/issues/35
notifications:
  email:
    - m.a.laporte@cgiar.org
